version = 0.1

[local.deploy.parameters]
stack_name = "price-list-lambda-stack"
resolve_s3 = true
s3_prefix = "price-list-lambda-stack"
profile = "ffresco"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
