spring:
  cloud:
    function:
      # Local/default function.
      # SAM/AWS overrides this value with SPRING_CLOUD_FUNCTION_DEFINITION=apiGatewayRouter.
      definition: health
      #definition: getHealthRouteHandler
  application:
    name: totem-backend-price-list
  main:
    web-application-type: servlet

app:
  aws:
    region: ${AWS_REGION:sa-east-1}
    dynamodb:
      table-name: ${TOTEM_CORE_TABLE_NAME:totem-core-local}
      endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}