spring:
  cloud:
    function:
      # Local/default function.
      # SAM/AWS overrides this value with SPRING_CLOUD_FUNCTION_DEFINITION=apiGatewayRouter.
      definition: health
      #definition: getHealthRouteHandler
